In [11]:
from torch import nn
import torch
from torch import tensor

### Dataset

In [12]:
x_data = tensor([[1.0,1.0], [2.0,1.0], [3.0,1.0],[4.0,1.0],[5.0,1.0]])
y_data = tensor([[2.0,0.0], [3.0,1.0], [4.0,2.0], [5.0,3.0], [6.0,4.0]])

### Model

In [13]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(2, 2)  # two in and two out

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [14]:
model = Model()

### Optimizer and loss

In [15]:
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

### Train

In [16]:
for epoch in range(100):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x_data)

    # 2) Compute and print loss
    loss = criterion(y_pred, y_data)
    print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


Epoch: 0 | Loss: 96.26226806640625 
Epoch: 1 | Loss: 9.751250267028809 
Epoch: 2 | Loss: 3.341434955596924 
Epoch: 3 | Loss: 2.7156646251678467 
Epoch: 4 | Loss: 2.5169408321380615 
Epoch: 5 | Loss: 2.3585312366485596 
Epoch: 6 | Loss: 2.2119712829589844 
Epoch: 7 | Loss: 2.0746543407440186 
Epoch: 8 | Loss: 1.945871353149414 
Epoch: 9 | Loss: 1.8250830173492432 
Epoch: 10 | Loss: 1.7117934226989746 
Epoch: 11 | Loss: 1.6055359840393066 
Epoch: 12 | Loss: 1.5058740377426147 
Epoch: 13 | Loss: 1.4123984575271606 
Epoch: 14 | Loss: 1.32472562789917 
Epoch: 15 | Loss: 1.2424944639205933 
Epoch: 16 | Loss: 1.1653683185577393 
Epoch: 17 | Loss: 1.0930289030075073 
Epoch: 18 | Loss: 1.025180697441101 
Epoch: 19 | Loss: 0.9615435004234314 
Epoch: 20 | Loss: 0.9018568992614746 
Epoch: 21 | Loss: 0.8458751440048218 
Epoch: 22 | Loss: 0.7933681011199951 
Epoch: 23 | Loss: 0.7441209554672241 
Epoch: 24 | Loss: 0.6979303359985352 
Epoch: 25 | Loss: 0.6546071171760559 
Epoch: 26 | Loss: 0.613973140

### Test

In [17]:
res = model(tensor([[7.0,1.0]]))

In [18]:
res

tensor([[8.0018, 5.9261]], grad_fn=<AddmmBackward0>)

In [19]:
model.linear.weight

Parameter containing:
tensor([[ 1.0005,  0.6790],
        [ 0.9785, -0.4029]], requires_grad=True)

In [20]:
model.linear.bias

Parameter containing:
tensor([ 0.3192, -0.5206], requires_grad=True)