In [ ]:
from torch import nn
import torch
from torch import tensor

In [ ]:
# Data
x = tensor([[1.0], [2.0], [3.0]])
y = tensor([[2.0], [4.0], [6.0]])

In [ ]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(1, 1)  # One in and one out

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

In [ ]:
model = Model()

In [ ]:
# Optimizer and loss
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
# Train
for epoch in range(100):
    # 1) Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # 2) Compute and print loss
    loss = criterion(y_pred, y)
    print(f'Epoch: {epoch} | Loss: {loss.item()} ')

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch: 0 | Loss: 27.348852157592773 
Epoch: 1 | Loss: 12.313880920410156 
Epoch: 2 | Loss: 5.618741512298584 
Epoch: 3 | Loss: 2.6362876892089844 
Epoch: 4 | Loss: 1.306642770767212 
Epoch: 5 | Loss: 0.7128117084503174 
Epoch: 6 | Loss: 0.44657033681869507 
Epoch: 7 | Loss: 0.32618966698646545 
Epoch: 8 | Loss: 0.27076879143714905 
Epoch: 9 | Loss: 0.2442927360534668 
Epoch: 10 | Loss: 0.23072773218154907 
Epoch: 11 | Loss: 0.2229360044002533 
Epoch: 12 | Loss: 0.2177392840385437 
Epoch: 13 | Loss: 0.21372324228286743 
Epoch: 14 | Loss: 0.2102566659450531 
Epoch: 15 | Loss: 0.20705938339233398 
Epoch: 16 | Loss: 0.20400525629520416 
Epoch: 17 | Loss: 0.201038658618927 
Epoch: 18 | Loss: 0.19813388586044312 
Epoch: 19 | Loss: 0.1952795386314392 
Epoch: 20 | Loss: 0.19246989488601685 
Epoch: 21 | Loss: 0.18970239162445068 
Epoch: 22 | Loss: 0.1869754195213318 
Epoch: 23 | Loss: 0.18428808450698853 
Epoch: 24 | Loss: 0.18163947761058807 
Epoch: 25 | Loss: 0.17902904748916626 
Epoch: 26 | 

In [ ]:
# Test
res = model(tensor([[4.0]]))

In [ ]:
res

tensor([[7.7153]], grad_fn=<AddmmBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[1.8351]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.3748], requires_grad=True)